services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    env_file:
      - ./.env
  migrate:
    build:
      context: .
      dockerfile: migration.Dockerfile
    command: -database ${DATABASE_URL} up
    env_file:
      - ./.env
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
      - ./.env
    ports:
      - "8980"

volumes:
  postgres_data: